# Generated by Django 6.0.6 on 2026-07-11 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0005_tag_like"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="blogs", to="blogs.tag"
            ),
        ),
    ]
